### ISSUE TITLE
Error in JSDOC_ERROR

### ISSUE THREAD

**Issue by escael** [viljamis/vue-design-system#209]
Hello, I have the following error:

Node version: v14.4.0
NPM Version: 6.14.5

`JSDOC_ERROR: /Users/emarrero/www/sistema/node_modules/requizzle/lib/requizzle.js:45
	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
	               ^

TypeError: Cannot read property '0' of null
    at isNativeModule (/Users/emarrero/www/sistema/node_modules/requizzle/lib/requizzle.js:45:17)
    at Requizzle.requizzle (/Users/emarrero/www/sistema/node_modules/requizzle/lib/requizzle.js:82:6)
    at infectProxy (/Users/emarrero/www/sistema/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (/Users/emarrero/www/sistema/node_modules/requizzle/lib/loader.js:101:11)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/emarrero/www/sistema/node_modules/jsdoc/lib/jsdoc/fs.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Object.load (/Users/emarrero/www/sistema/node_modules/requizzle/lib/loader.js:112:15)`

I have changed the node versions to 12, and the same is still happening. Lift server but don't render components.

Thanks.

**Comment by escael** [comment]
I have updated the entire dependency package and it has been fixed.

**Comment by juanbrujo** [comment]
although it works error still exists, prints on the console

node v.12.9.1
npm v.6.14.8
